/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/sofa.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cushions.geometry} material={materials.Cushions} />
      <mesh geometry={nodes.Leather.geometry} material={materials.Leather} />
      <mesh geometry={nodes.Legs.geometry} material={materials.Legs} />
      <mesh geometry={nodes.Wood.geometry} material={materials.Wood} />
    </group>
  )
}

useGLTF.preload('/sofa.glb')
